# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'final.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import PlotWidget
import numpy as np
import pyqtgraph as pg


class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		MainWindow.setObjectName("Предсказатель")
		MainWindow.resize(690, 503)
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
		self.layoutWidget.setGeometry(QtCore.QRect(41, 31, 94, 171))
		self.layoutWidget.setObjectName("layoutWidget")
		self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
		self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout_2.setObjectName("verticalLayout_2")
		self.label = QtWidgets.QLabel(self.layoutWidget)
		self.label.setObjectName("label")
		self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignRight)
		self.label_2 = QtWidgets.QLabel(self.layoutWidget)
		self.label_2.setObjectName("label_2")
		self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignRight)
		self.label_3 = QtWidgets.QLabel(self.layoutWidget)
		self.label_3.setObjectName("label_3")
		self.verticalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignRight)
		self.label_4 = QtWidgets.QLabel(self.layoutWidget)
		self.label_4.setObjectName("label_4")
		self.verticalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignRight)
		self.label_5 = QtWidgets.QLabel(self.layoutWidget)
		self.label_5.setObjectName("label_5")
		self.verticalLayout_2.addWidget(self.label_5, 0, QtCore.Qt.AlignRight)
		self.label_6 = QtWidgets.QLabel(self.layoutWidget)
		self.label_6.setObjectName("label_6")
		self.verticalLayout_2.addWidget(self.label_6, 0, QtCore.Qt.AlignRight)
		self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
		self.groupBox.setGeometry(QtCore.QRect(21, 11, 211, 221))
		self.groupBox.setObjectName("groupBox")
		self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
		self.layoutWidget_2.setGeometry(QtCore.QRect(130, 20, 73, 171))
		self.layoutWidget_2.setObjectName("layoutWidget_2")
		self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
		self.verticalLayout.setContentsMargins(0, 0, 0, 0)
		self.verticalLayout.setObjectName("verticalLayout")
		self.plainTextEdit = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
		self.plainTextEdit.setObjectName("plainTextEdit")
		self.verticalLayout.addWidget(self.plainTextEdit)
		self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
		self.plainTextEdit_2.setObjectName("plainTextEdit_2")
		self.verticalLayout.addWidget(self.plainTextEdit_2)
		self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
		self.plainTextEdit_3.setObjectName("plainTextEdit_3")
		self.verticalLayout.addWidget(self.plainTextEdit_3)
		self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
		self.plainTextEdit_4.setObjectName("plainTextEdit_4")
		self.verticalLayout.addWidget(self.plainTextEdit_4)
		self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
		self.plainTextEdit_5.setObjectName("plainTextEdit_5")
		self.verticalLayout.addWidget(self.plainTextEdit_5)
		self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.layoutWidget_2)
		self.plainTextEdit_6.setObjectName("plainTextEdit_6")
		self.verticalLayout.addWidget(self.plainTextEdit_6)
		self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
		self.groupBox_2.setGeometry(QtCore.QRect(30, 140, 191, 71))
		self.groupBox_2.setObjectName("groupBox_2")
		self.label_7 = QtWidgets.QLabel(self.groupBox_2)
		self.label_7.setGeometry(QtCore.QRect(10, 10, 51, 21))
		self.label_7.setObjectName("label_7")
		self.graphicsView = PlotWidget(self.centralwidget)
		self.graphicsView.setGeometry(QtCore.QRect(260, 20, 311, 201))
		self.graphicsView.setObjectName("graphicsView")
		self.graphicsView_2 = PlotWidget(self.centralwidget)
		self.graphicsView_2.setGeometry(QtCore.QRect(20, 240, 651, 221))
		self.graphicsView_2.setObjectName("graphicsView_2")
		self.pushButton = QtWidgets.QPushButton(self.centralwidget)
		self.pushButton.setGeometry(QtCore.QRect(584, 112, 91, 41))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.pushButton.setFont(font)
		self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color:rgba(85, 98, 112, 255);\n"
"border-radius:30px;\n"
"}\n"
"QPushButton#pushButton:hover{\n"
"color: rgba(155, 168, 182, 220);\n"
"}\n"
"QPushButton#pushButton:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"color: rgba(115, 128, 142, 255);\n"
"}\n"
"")
		self.pushButton.setObjectName("pushButton")
		self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
		self.pushButton_2.setGeometry(QtCore.QRect(584, 162, 91, 41))
		font = QtGui.QFont()
		font.setPointSize(12)
		font.setBold(True)
		font.setWeight(75)
		self.pushButton_2.setFont(font)
		self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
		self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"background-color: rgba(0, 0, 0, 0);\n"
"color:rgba(85, 98, 112, 255);\n"
"border-radius:30px;\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"color: rgba(155, 168, 182, 220);\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"color: rgba(115, 128, 142, 255);\n"
"}\n"
"")
		self.pushButton_2.setObjectName("pushButton_2")
		self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
		self.plainTextEdit_7.setGeometry(QtCore.QRect(620, 20, 51, 21))
		self.plainTextEdit_7.setObjectName("plainTextEdit_7")
		self.plainTextEdit_8 = QtWidgets.QPlainTextEdit(self.centralwidget)
		self.plainTextEdit_8.setGeometry(QtCore.QRect(620, 50, 51, 21))
		self.plainTextEdit_8.setObjectName("plainTextEdit_8")
		self.plainTextEdit_9 = QtWidgets.QPlainTextEdit(self.centralwidget)
		self.plainTextEdit_9.setGeometry(QtCore.QRect(620, 80, 51, 21))
		self.plainTextEdit_9.setObjectName("plainTextEdit_9")
		self.label_8 = QtWidgets.QLabel(self.centralwidget)
		self.label_8.setGeometry(QtCore.QRect(600, 20, 16, 16))
		self.label_8.setObjectName("label_8")
		self.label_9 = QtWidgets.QLabel(self.centralwidget)
		self.label_9.setGeometry(QtCore.QRect(600, 50, 20, 20))
		self.label_9.setObjectName("label_9")
		self.label_10 = QtWidgets.QLabel(self.centralwidget)
		self.label_10.setGeometry(QtCore.QRect(597, 80, 20, 20))
		self.label_10.setObjectName("label_10")
		self.groupBox_2.raise_()
		self.groupBox.raise_()
		self.layoutWidget.raise_()
		self.graphicsView.raise_()
		self.graphicsView_2.raise_()
		self.pushButton.raise_()
		self.pushButton_2.raise_()
		self.plainTextEdit_7.raise_()
		self.plainTextEdit_8.raise_()
		self.plainTextEdit_9.raise_()
		self.label_8.raise_()
		self.label_9.raise_()
		self.label_10.raise_()
		MainWindow.setCentralWidget(self.centralwidget)
		self.menubar = QtWidgets.QMenuBar(MainWindow)
		self.menubar.setGeometry(QtCore.QRect(0, 0, 690, 21))
		self.menubar.setObjectName("menubar")
		MainWindow.setMenuBar(self.menubar)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)

		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)

		self.pushButton_2.clicked.connect(lambda: self.draw())
		self.pushButton.clicked.connect(lambda: self.clear())

	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "Предсказатель"))
		self.label.setText(_translate("MainWindow", "Кол-во отсчетов: "))
		self.label_2.setText(_translate("MainWindow", "Шум %:"))
		self.label_3.setText(_translate("MainWindow", "Начало:"))
		self.label_4.setText(_translate("MainWindow", "Конец:"))
		self.label_5.setText(_translate("MainWindow", "k:"))
		self.label_6.setText(_translate("MainWindow", "b:"))
		self.groupBox.setTitle(_translate("MainWindow", "Parameters"))
		self.plainTextEdit.setPlainText(_translate("MainWindow", "100"))
		self.plainTextEdit_2.setPlainText(_translate("MainWindow", "20"))
		self.plainTextEdit_3.setPlainText(_translate("MainWindow", "100"))
		self.plainTextEdit_4.setPlainText(_translate("MainWindow", "1000"))
		self.plainTextEdit_5.setPlainText(_translate("MainWindow", "3"))
		self.plainTextEdit_6.setPlainText(_translate("MainWindow", "4"))
		self.groupBox_2.setTitle(_translate("MainWindow", "Уравнение прямой"))
		self.label_7.setText(_translate("MainWindow", "y = kx + b"))
		self.pushButton.setText(_translate("MainWindow", "Clear"))
		self.pushButton_2.setText(_translate("MainWindow", "Plot"))
		self.plainTextEdit_7.setPlainText(_translate("MainWindow", "10"))
		self.plainTextEdit_8.setPlainText(_translate("MainWindow", "5"))
		self.plainTextEdit_9.setPlainText(_translate("MainWindow", "90"))
		self.label_8.setText(_translate("MainWindow", "N"))
		self.label_9.setText(_translate("MainWindow", "n1"))
		self.label_10.setText(_translate("MainWindow", "n2"))
		self.graphicsView_2.addLegend()
		self.graphicsView.setLabel('left', 'Отклонение (среднее)')
		self.graphicsView.setLabel('bottom', 'Шум (%)')

	def draw(self):
		self.graphicsView_2.clear()
		Alpha1 = float(self.plainTextEdit_2.toPlainText())
		k = float(self.plainTextEdit_5.toPlainText())
		b = float(self.plainTextEdit_6.toPlainText())
		N = int(self.plainTextEdit.toPlainText())
		n1 = int(self.plainTextEdit_3.toPlainText())
		n2 = int(self.plainTextEdit_4.toPlainText())

		NN = int(self.plainTextEdit_7.toPlainText())
		nn1 = int(self.plainTextEdit_8.toPlainText())
		nn2 = int(self.plainTextEdit_9.toPlainText())

		###################################################################
		# Задание сигнал + шум
		x = np.linspace(n1, n2, N)
		y = []
		for i in range(0, N):
			s = k*x[i]+b
			y.append(s)

		# Задание аддитивного белого гауссовского шума
		def noise(Alpha1, y):
			Noise = []
			ENoise = 0
			for i in range(0, len(y)):
				q = 0
				for j in range(0, 12):
					q += np.random.uniform(0, 2) - 1 # суммирование 12 случайных чисел
				q = q/12
				Noise.append(q)
				ENoise += q * q

			ESignal = 0
			for i in range(0, len(y)):
				ESignal += y[i] * y[i]

			Alpha = Alpha1/100
			Betta = np.sqrt(Alpha * ESignal / ENoise)
			noise = []
			for i in range(0, len(y)):
				noise.append(Betta * Noise[i])

			Y = [k1 + k2 for k1, k2 in zip(y, noise)]

			return Y

		def matrix(x, Y, N):
			x_matrix = []
			for i in range(0, N):
				x_matrix.append([1, x[i]])

			y_matrix = []
			for i in range(0, N):
				y_matrix.append(Y[i])

			x_matrix_T = np.transpose(x_matrix)

			x_res = x_matrix_T.dot(x_matrix)
			y_res = x_matrix_T.dot(y_matrix)

			x_res_inv = np.linalg.inv(x_res)
			Y_new = x_res_inv.dot(y_res)

			# Коеффициенты
			a0 = Y_new[0] 
			a1 = Y_new[1]

			yyy = []
			for i in range(0, N):
				yyy.append(a0 + a1*x[i])

			return yyy

		def error(yyy, Y, N):
			uuu = []
			sum = 0
			for i in range(0, N):
				uuu.append(abs(yyy[i]-Y[i]))
				sum += uuu[i]
			osh = sum/N

			return osh

		

		Y = noise(Alpha1, y)
		yyy = matrix(x, Y, N)

		
		
		self.graphicsView_2.plot(x, Y, name='Случайный процесс')
		self.graphicsView_2.plot(x, yyy, pen = 'r', name='Прогноз')


		po_int = np.linspace(nn1, nn2, NN)
		po_int1 = []

		for i in range(0, NN):
			Y2 = noise(po_int[i], y)
			osh = error(yyy, Y2, N) # Меняется Y
			po_int1.append(osh) # Массив из средней ошибки

		scatter = pg.ScatterPlotItem(
			size=10, brush=pg.mkBrush(30, 255, 35, 255))
		scatter.addPoints(po_int, po_int1)
		self.graphicsView.addItem(scatter)

	def clear(self):
		self.graphicsView.clear()


if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())
